/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yuanc
 */
public class staffDeclarePg extends javax.swing.JFrame {

    int a = 0;
    String days = "";
    String id;
    String role;

    /**
     * Creates new form staffDeclarePg
     */
    public staffDeclarePg() {
        initComponents();
        setTitle("Staff Declaration");
    }

    public staffDeclarePg(String id, String role) {
        initComponents();
        setTitle("Staff Declaration");
        this.id = id;
        this.role = role;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monCB = new javax.swing.JCheckBox();
        wedCB = new javax.swing.JCheckBox();
        thurCB = new javax.swing.JCheckBox();
        tueCB = new javax.swing.JCheckBox();
        friCB = new javax.swing.JCheckBox();
        satCB = new javax.swing.JCheckBox();
        sunCB = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        monCB.setText("Monday");
        monCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monCBActionPerformed(evt);
            }
        });

        wedCB.setText("Wednesday");
        wedCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedCBActionPerformed(evt);
            }
        });

        thurCB.setText("Thursday");
        thurCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thurCBActionPerformed(evt);
            }
        });

        tueCB.setText("Tuesday");
        tueCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tueCBActionPerformed(evt);
            }
        });

        friCB.setText("Friday");
        friCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friCBActionPerformed(evt);
            }
        });

        satCB.setText("Saturday");
        satCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satCBActionPerformed(evt);
            }
        });

        sunCB.setText("Sunday");
        sunCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunCBActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(submitButton)
                                                        .addComponent(sunCB)
                                                        .addComponent(satCB)
                                                        .addComponent(friCB)
                                                        .addComponent(tueCB)
                                                        .addComponent(thurCB)
                                                        .addComponent(wedCB)
                                                        .addComponent(monCB)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(messageLabel)))
                                .addContainerGap(102, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(monCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tueCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wedCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thurCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(friCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(satCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sunCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34,
                                        Short.MAX_VALUE)
                                .addComponent(messageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(submitButton)
                                .addGap(29, 29, 29)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        messageLabel.setText(a + " days declared : " + days + "\nId is: " + id + "\nRole is: " + role);
        declareSlotsController dsC = new declareSlotsController();
        boolean declaredSuccess = dsC.declareSlots(role, Integer.parseInt(id), days);
        displayMsg(declaredSuccess);
    }// GEN-LAST:event_submitButtonActionPerformed

    private void displayMsg(boolean t) {
        if (t) {
            messageLabel.setText(days + " has been added");
        } else {
            messageLabel.setText("Declaration failed");
        }
    }

    private void monCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_monCBActionPerformed
        // TODO add your handling code here:
        if (monCB.isSelected() == true) {
            a++;
            days += "MON, ";
        } else if (monCB.isSelected() == false) {
            a--;
            String newDays = days.replace("MON, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_monCBActionPerformed

    private void tueCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tueCBActionPerformed
        // TODO add your handling code here:
        if (tueCB.isSelected() == true) {
            a++;
            days += "TUE, ";
        } else if (tueCB.isSelected() == false) {
            a--;
            String newDays = days.replace("TUE, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_tueCBActionPerformed

    private void wedCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_wedCBActionPerformed
        // TODO add your handling code here:
        if (wedCB.isSelected() == true) {
            a++;
            days += "WED, ";
        } else if (wedCB.isSelected() == false) {
            a--;
            String newDays = days.replace("WED, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_wedCBActionPerformed

    private void thurCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thurCBActionPerformed
        // TODO add your handling code here:
        if (thurCB.isSelected() == true) {
            a++;
            days += "THU, ";
        } else if (thurCB.isSelected() == false) {
            a--;
            String newDays = days.replace("THU, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_thurCBActionPerformed

    private void friCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_friCBActionPerformed
        // TODO add your handling code here:
        if (friCB.isSelected() == true) {
            a++;
            days += "FRI, ";
        } else if (friCB.isSelected() == false) {
            a--;
            String newDays = days.replace("FRI, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_friCBActionPerformed

    private void satCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_satCBActionPerformed
        // TODO add your handling code here:
        if (satCB.isSelected() == true) {
            a++;
            days += "SAT, ";
        } else if (satCB.isSelected() == false) {
            a--;
            String newDays = days.replace("SAT, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_satCBActionPerformed

    private void sunCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sunCBActionPerformed
        // TODO add your handling code here:
        if (sunCB.isSelected() == true) {
            a++;
            days += "SUN, ";
        } else if (sunCB.isSelected() == false) {
            a--;
            String newDays = days.replace("SUN, ", "");
            days = newDays;
        }
    }// GEN-LAST:event_sunCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffDeclarePg.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffDeclarePg.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffDeclarePg.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffDeclarePg.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffDeclarePg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox friCB;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JCheckBox monCB;
    private javax.swing.JCheckBox satCB;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox sunCB;
    private javax.swing.JCheckBox thurCB;
    private javax.swing.JCheckBox tueCB;
    private javax.swing.JCheckBox wedCB;
    // End of variables declaration//GEN-END:variables
}
